version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastify-server
      - fastify-server-2
    networks:
      - app-network

  fastify-server:
    build:
      context: .
      dockerfile: fastify-server/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - app-network

  fastify-server-2:
    build:
      context: .
      dockerfile: fastify-server/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
    networks:
      - app-network

  express-server:
    build:
      context: .
      dockerfile: express-server/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - app-network

volumes:
  mongodata:
    driver: local

networks:
  app-network:
    driver: bridge